#!/usr/bin/ruby
require 'yaml'

TASK_FILE = ".task"
COMPANY = "artsy"

# also supports using the .gitconfig
ME = "orta"

unless File.exists TASK_FILE
  p "You have not started a task here!"
  return
end

if `git status -s` == ""
  p "You have changes to commit still"
  return
end

# support using the .gitconfig to find a username
if File.exists "~/.gitconfig"
  config = File.read("~/.gitconfig")
  if config.include? "user = "
    ME = config.split("user = ")[1].split("\n")[0]
  end
end

task = YAML.load_file(.task)
p "Finishing up #{task["title"]}"

# Make a dummy commit to close the issue once the PR is merged
`git commit --allow-empty -m "Closes #{task["id"]} - #{task["title"]}"`

branch = `echo (git-branch)`
p "Pushing to #{branch} on origin"

`git push origin (git-branch)`

current_folder = `(basename (pwd))`
site = "https://github.com/#{ME}/#{current_folder}/pull/new/#{COMPANY}:master...#{branch}";
p "Opening a PR to #{site}"

`open #{site}`