#!/usr/bin/ruby
require 'yaml'

TASK_FILE = ".task"
COMPANY = "artsy"
ME = "orta"

unless File.exists? TASK_FILE
  p "You have not started a task here!"
  return
end

if `git status -s` == ""
  p "You have changes to commit still"
  return
end

task = YAML.load_file(TASK_FILE)

p "Finishing up #{task[:title]}"

# Make a dummy commit to close the issue once the PR is merged
`git commit --allow-empty -m "Closes #{task[:id]} - #{task[:title]}" `

branch = `git rev-parse --abbrev-ref HEAD`.strip
p "Pushing to #{branch} on origin"

`git push origin #{branch}`

current_folder = File.basename(Dir.getwd)
site = "https://github.com/#{ME}/#{current_folder}/pull/new/#{COMPANY}:master...#{branch}";
p "Opening a PR to #{site}"

`rm #{TASK_FILE}`
`open #{site}`